### ISSUE TITLE
Unable to quickload cl-mock

### ISSUE THREAD

**Issue by adampaulukanis** [Ferada/cl-mock#4]
Hi, I am new to lisp and perhaps am doing something wrong here.

`$ uname
Darwin`

`$ clisp
  i i i i i i i       ooooo    o        ooooooo   ooooo   ooooo
  I I I I I I I      8     8   8           8     8     o  8    8
  I  \ `+' /  I      8         8           8     8        8    8
   \  `-+-'  /       8         8           8      ooooo   8oooo
    `-__|__-'        8         8           8           8  8
        |            8     o   8           8     o     8  8
  ------+------       ooooo    8oooooo  ooo8ooo   ooooo   8

Welcome to GNU CLISP 2.49 (2010-07-07) <http://clisp.cons.org/>

Copyright (c) Bruno Haible, Michael Stoll 1992, 1993
Copyright (c) Bruno Haible, Marcus Daniels 1994-1997
Copyright (c) Bruno Haible, Pierpaolo Bernardi, Sam Steingold 1998
Copyright (c) Bruno Haible, Sam Steingold 1999-2000
Copyright (c) Sam Steingold, Bruno Haible 2001-2010

Type :h and hit Enter for context help.

;; Loading file /Users/adam/.clisprc.lisp ...
;;  Loading file /Users/adam/quicklisp/setup.lisp ...
;;   Loading file /Users/adam/quicklisp/asdf.lisp ...
;;   Loaded file /Users/adam/quicklisp/asdf.lisp
;;  Loaded file /Users/adam/quicklisp/setup.lisp
;; Loaded file /Users/adam/.clisprc.lisp
[1]> (ql:quickload "cl-mock")
To load "cl-mock":
  Load 1 ASDF system:
    cl-mock
; Loading "cl-mock"
On CLISP, we cannot add method to DESCRIBE-OBJECT, so you cannot enjoy extended documentations for various namespaces.
** - Continuable Error
in #:|364 368 (TRIVIAL-CLTL2:DEFINE-DECLARATION OPTIMIZER (SPECIFIER ENV) ...)-31| in lines 364..368 : Misplaced declaration:
     (DECLARE (IGNORABLE ENV))
If you continue (by typing 'continue'): Ignore the error and proceed
The following restarts are also available:
RETRY          :R1      Retry compiling #<CL-SOURCE-FILE "trivia.level2" "impl">.
ACCEPT         :R2      Continue, treating compiling #<CL-SOURCE-FILE "trivia.level2" "impl"> as having been successful.
RETRY          :R3      Retry ASDF operation.
CLEAR-CONFIGURATION-AND-RETRY :R4 Retry ASDF operation after resetting the configuration.
ABORT          :R5      Give up on "cl-mock"
REGISTER-LOCAL-PROJECTS :R6 Register local projects and try again.
ABORT          :R7      Abort main loop
Break 1 TRIVIA.LEVEL2.IMPL[2]> :q
[3]> (exit)
Bye.
$ `

**Comment by mdbergmann** [comment]
Seems Clisp has a problem with Trivia.
Can you CCL, ECL or SBCL?

**Comment by mdbergmann** [comment]
Optima was replaced by Trivia some time ago because Optima is not maintained anymore.

However, if you need to stick to Clisp, you could get checkout the commit of cl-mock before the change to Trivia if that is of any help.

**Comment by adampaulukanis** [comment]
Thanks! I am using now SBCL.

**Comment by mdbergmann** [comment]
Awesome. Can you please close the ticket as this is not a cl-mock problem.
